services:
  postgres:
    image: postgres:17
    container_name: auth-pg
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - auth-pg-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: auth-api
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      Jwt__Key: ${JWT_KEY}
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5075:8080"

volumes:
  auth-pg-data: